mode: chatops
openPR: true
autoCloseIssue: true
autoLinkIssue: true
autoDeleteBranch: true
conventionalPrTitles: true
conventionalStyle: semver
copyIssueProjectsToPR: true
conventionalLabels:
  my-prefix:
    my-label: ':rocket:'
