branchName: '${issue.number}-${issue.title}'
mode: auto
autoCloseIssue: true
openPR: true
copyIssueDescriptionToPR: true
copyIssueMilestoneToPR: true
copyIssueProjectsToPR: true
experimental:
  branchNameArgument: true
